### PR TITLE
chore(element-templates): Update element template descriptions and add keywords

### LINKED ISSUE #3089: Update template descriptions and add keywords to improve refactorings suggestions
__What should we do?__

The ✨ feature for selected elements in Web Modeler suggests connectors based on an element's name. The suggestions are based on the name and description of the connector templates and therefore the quality of suggestions depends on those.

image

The latest version of the ✨ also takes into account keywords that were added to a template. For example, the following template

```json
{
  "$schema": "https://unpkg.com/@camunda/zeebe-element-templates-json-schema/resources/schema.json",
  "name": "Twitter Connector",
  "id": "io.camunda.connectors.Twitter",
  "version": 1,
  "description": "Post and manage tweets on Twitter",
  "metadata": {
    "keywords": [
      "create tweet",
      "delete tweet",
      "quote tweet",
      "reply to tweet",
      "retweet"
    ]
  },
  "category": {
    "id": "connectors",
    "name": "Connectors"
  },
  "appliesTo": [
    "bpmn:Task"
  ],
  "properties": []
}
```

has a `keywords` field with relevant keywords. If an element's name mentions replying to a tweet the connector will be suggested based on the matching keyword.

__Why should we do it?__

To improve the quality of suggestions.

Related to https://github.com/bpmn-io/refactorings/pull/27

### PR DESCRIPTION
**Pull request by philippfromme**
## Description

* adds support for a `metadata` property with `keywords` ([already supported by element templates](https://github.com/camunda/element-templates-json-schema/blob/0c7c1a43279859d8679ab09deb657cb73a6a9cfb/packages/element-templates-json-schema-shared/src/defs/base.json#L89))
* in order for refactorings feature to be able to suggest better refactorings
  * updates descriptions of existing element templates
  * adds keywords to existing element templates

## Related issues

Closes #3089

## Checklist

- [x] PR has a **milestone** or the `no milestone` label.

### CODE REVIEW

**Comment by philippfromme** [comment]
@johnBgood Can you have a look whether the `update description and add keywords` commits look okay? If yes, I'd continue. Also, I'm not sure why the tests are failing. I've used `@ElementTemplate.Metadata` in the same way as in the example.

**Comment by johnBgood** [comment]
You needed to run `mvn spotless:apply`, it was just a listing issue 👍 
I did that, let's see if the tests are passing now. 

I'll check the commits later today, or tomorrow.

**Comment by johnBgood** [comment]
@philippfromme Commits look good! :)

**Comment by sbuettner** [comment]
Hey @philippfromme, any plans when you want to merge these changes?

Please let us know so we can add the milestone.

**Comment by philippfromme** [comment]
@sbuettner I'd love to continue working on this but I won't have time until the end of the year. One option is to merge the changes I've made so far. Any further improvements like adding keywords to more connectors can be done at any time. What do you think?

**Comment by philippfromme** [comment]
I've marked it as ready for review.

**Comment by sbuettner** [comment]
Happy to merge this after @johnBgood did the review.

To see these changes in the modeler(s) it would require quite some additional work as we will have to re-generate all element templates and update them in the web-modeler. 

Hence I would merge but postpone these steps after you did all your updates.

**Comment by sbuettner** [comment]
@philippfromme Can you take care of the rebase? Might be the reason why the tests are failing.

**Review by johnBgood — APPROVED** [review]
Thank you for this great work :)

**Comment by philippfromme** [comment]
@johnBgood I think I fixed all the formatting issues. However, there still seem to be errors. Maybe you could have a look.

**Review by johnBgood — APPROVED** [review]

**Comment by johnBgood** [comment]
@philippfromme We can merge it now. Be aware that we also need to update the templates in [the web-modeler repo](https://github.com/camunda/web-modeler/tree/main/webapp/src/App/Pages/Diagram/BpmnJSExtensions/connectorsExtension/.camunda/element-templates)

**Comment by philippfromme** [comment]
Who's merging? One of you or should I?

**Comment by philippfromme** [comment]
Thanks, @johnBgood! 💪🏻

**Pull request merged**
