### PR TITLE
Fix for not being able to set details on an UNKNOWN/DOWN Health instance

### PR DESCRIPTION
**Pull request by Pucilowski**
## Description

Could not previously set details map on a unknown/down instance

## Related issues

closes #

### CODE REVIEW

**Review by sbuettner — APPROVED** [review]

**Review by sbuettner — APPROVED** [review]

**Comment by sbuettner** [comment]
@Pucilowski please sign the license agreement so we can merge your PR. Thank you!

**Comment by sbuettner** [comment]
@Pucilowski Thanks again for finding it. Please sign the CLA otherwise we will provide the fix ouselves to be able to merge it.

**Comment by sbuettner** [comment]
Hey @Pucilowski please provide your CLA signing until the end of the week. Otherwise we have to close the PR and fix it ourselves. Thank you for the support.

**Comment by Pucilowski** [comment]
signed now :)

**Review by igpetrov — APPROVED** [review]

**Pull request merged**
