### PR TITLE
chore(qa): Automate QA process

### PR DESCRIPTION
**Pull request by johnBgood**
## Related issues

closes #

## Checklist

- [ ] PR has a **milestone** or the `no milestone` label.

### CODE REVIEW

**Comment by sbuettner** [comment]
Hey @johnBgood nice work. Did you consider to use c8 to make this more maintainable?

**Comment by johnBgood** [comment]
@sbuettner Yes, and this might be the way to move forward. This PR is just a test, not the final solution and it doesn't work using project cards anyway :D

**Comment by slolatte** [comment]
Hello

**Comment by slolatte** [comment]
Hello

**Comment by slolatte** [comment]
Hello

**Comment by slolatte** [comment]
Hello

**Comment by slolatte** [comment]
Hello

**Comment by slolatte** [comment]
Hello

**Comment by slolatte** [comment]
Hello

**Comment by slolatte** [comment]
Hello

**Comment by slolatte** [comment]
Hello

**Comment by sbuettner** [comment]
Hello

**Comment by johnBgood** [comment]
Hello

**Comment by johnBgood** [comment]
Hello

**Comment by johnBgood** [comment]
Hello

**Comment by johnBgood** [comment]
Hello

**Comment by johnBgood** [comment]
Hello

**Comment by johnBgood** [comment]
# QA information
## Test Environment
- Environment:
  - [ ] SaaS only
  - [ ] SM only
  - [ ] Both
- [ ] Connectors version: N/A

## Test Scope
*Please describe the test scope, happy path, edge cases that come to your mind, and whatever you think might relevant to test*

## Test Data
*Please provide the test data, if needed (files, URLs, code snippets, FEEL expressions)*

**Pull request closed without merging**
