### PR TITLE
chore(soap): update SOAP connector to the latest generator

### PR DESCRIPTION
**Pull request by igpetrov**
chore(soap): update SOAP connector to the latest generator

### CODE REVIEW

**Comment by johnBgood** [comment]
Not part of your issue but [SoapConnector](https://github.com/camunda/connectors/blob/2b4997bfc2219e5f3f7f6e18ef1bb48b602e482e/connectors/soap/src/main/java/io/camunda/connectors/soap/SoapConnector.java#L30) is the only one (I guess) with an empty `inputVariables` param. Is it on purpose?

**Comment by igpetrov** [comment]
> Not part of your issue but [SoapConnector](https://github.com/camunda/connectors/blob/2b4997bfc2219e5f3f7f6e18ef1bb48b602e482e/connectors/soap/src/main/java/io/camunda/connectors/soap/SoapConnector.java#L30) is the only one (I guess) with an empty `inputVariables` param. Is it on purpose?

Fair point for the normal circumstances, but the idea for this connector was to move it "as-is" from consulting repo. Refactoring planned as the next step.

**Comment by sbuettner** [comment]
@igpetrov I think its a valid concern and considered best practice. Would be great if you could quickly incorporate these changes.

**Comment by igpetrov** [comment]
> @igpetrov I think its a valid concern and considered best practice. Would be great if you could quickly incorporate these changes.

okay, shouldn't take long

**Comment by igpetrov** [comment]
Hi @Oleksiivanov,

Sorry for back-and-forth, could you please give one more review/approval?

Thank you!

**Pull request merged**
