### PR TITLE
Add RPC support to the RabbitMQ Connector

### LINKED ISSUE #1735: Use the RabbitMQ connector to make RPC calls
__Is your feature request related to a problem? Please describe.__

I want to use the RabbitMQ Connector to publish an RPC message.

This is actually suggested in a Camunda blog post a while ago: https://camunda.com/blog/2021/03/communication-between-loosely-coupled-microservices/

__Describe the solution you'd like__

There is a nice RPC pattern that RabbitMQ suggests here: https://www.rabbitmq.com/tutorials/tutorial-six-java.html

To make an RPC call to another application, you first publish a message, but fill in the `replyTo` and `correlationId` headers. These values can be autogenerated GUID's.

Next, you listen to the queue you have specified in the `replyTo` header (you should declare the queue before publishing, to avoid a race condition).

When a reply arrives at the queue, the correlationId should probably already match (since the queue name was also auto generated). This reply then gets send to the zeebe engine to complete the activity.

An timeout value can also be passed as a parameter to indicate when we should stop waiting for a RPC reply.

__Describe alternatives you've considered__

See here: https://forum.camunda.io/t/using-the-rabbitmq-connectors-to-make-rpc-calls/49799

__Additional context__

* https://www.rabbitmq.com/tutorials/tutorial-six-java.html
* https://camunda.com/blog/2021/03/communication-between-loosely-coupled-microservices/

### PR DESCRIPTION
**Pull request by michaelarnauts**
## Description

I've extended the RabbitMQ Connector to add RPC support based on the example here: https://www.rabbitmq.com/tutorials/tutorial-six-java.html

This is still a draft to get feedback about this. I'll also need to rebase this to `main` later.

Some code should probably be moved to a common model, but I'll keep it seperate for now to minimize code changes in unrelated files.

## Related issues

closes #1735

### CODE REVIEW

**Review by chillleader — COMMENTED** [review]
Thank you for raising this issue and taking the initiative here!

Looking at the implementation, I'm a bit concerned about job timeouts. If the RPC response timeout happens to be bigger than the job timeout, the connector invocation could be retried, creating a potential idempotency issue. I understand though that this approach may still work perfectly for you given the preconditions (hosting connectors on-premises => you are in control of the job timeout).

I discussed this with the @camunda/connectors team and we reached a consensus that we'd rather try to solve this on the modelling level, bootstrapping the existing outbound & inbound RabbitMQ connectors to create a reusable BPMN subprocess (similar to what I suggested [on the forum](https://forum.camunda.io/t/using-the-rabbitmq-connectors-to-make-rpc-calls/49799/2?u=chillleader)). We'd like to avoid maintaining a separate connector function tailored specifically for RMQ RPC.

Here's what we could do:
- If you prefer to proceed with the current solution, would you maybe consider publishing in our [community hub](https://github.com/camunda-community-hub)?
- Alternatively, we could try to solve the issues you've experienced with the modeling approach. For instance, if generating a UUID is something you're missing, it can also be implemented as a custom [FEEL function](https://camunda.github.io/feel-scala/docs/reference/developer-guide/function-provider-spi).

WDYT?

**Comment by michaelarnauts** [comment]
@chillleader thanks for reviewing.

I've first tried to do it with in the BPMN as suggested on the forums, but I ran into a few issues.
* There is no `UUID()` function to generate the callback queue and correlation ID. Not sure if it will be accepted, since it's not in the DMN, but I've opened an issue here: https://github.com/camunda/feel-scala/issues/796
* It's just a lot of work to model this in BPMN (probably in every process where i want to do a RPC call) while I feel that this should be a basic feature of the connector.

Regarding the timeout, doesn't this also occur with the other connectors?

I think we don't have another choice then to maintain the changes ourselves. I'm not sure about the legal possibilities of publishing my changes in the Connector HUB, since it's based on the current RabbitMQ Producer code, what doesn't have an open license. :(

**Comment by michaelarnauts** [comment]
Hmm, now thinking about it. Since the inbound connector requires Operate to register the callback (and therefore, requires a license), is it even possible to generate a UUID at runtime and have it register the queue? I thought that all inbound connectors were registered when the process is deployed.

**Comment by sbuettner** [comment]
> I thought that all inbound connectors were registered when the process is deployed.

Exactly. The deployed process definitions are fetched from Operator and scanned for inbound Connector definitions. There is one inbound Connector instance per process definition. They are not instantiated on a process level but on a process definition level.

> is it even possible to generate a UUID at runtime and have it register the queue

Outbound Connectors can be seen as singletons. You would therefore do everything inside the function. You could generate any identifier there and potentially cache it based on some key if that is needed.

**Comment by chillleader** [comment]
> is it even possible to generate a UUID at runtime and have it register the queue

What @sbuettner said above is true for most inbound connectors, but we also have an example where an inbound connector accesses process instance variables - it's the [HTTP Polling connector](https://github.com/camunda/connectors/blob/main/connectors/http/polling/src/main/java/io/camunda/connector/http/polling/HttpPollingConnector.java). Notice how it uses `InboundIntermediateConnectorContext` which is a modification of `InboundConnectorContext` that also exposes individual process instances. However this is much more complicated than a regular inbound or outbound connector.

> Regarding the timeout, doesn't this also occur with the other connectors?

True - we'll need to address this issue for other connectors too. There's a new Zeebe API that allows updating the timeout for activated jobs, we're currently considering exposing it in the connector context.

> it's based on the current RabbitMQ Producer code, what doesn't have an open license

Sadly, have to agree with you here. I guess the only viable option would be to eliminate the dependency on the OOTB connector.

**Pull request closed without merging**
